<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="$(SolutionDir)\shared\Functionals\**\*.*">
      <Link>Common\%(RecursiveDir)%(FileName)%(Extension)</Link>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Base\Abstractions\" />
    <Folder Include="Entries\" />
    <Folder Include="BrandAggregate\" />
    <Folder Include="CategoryAggregate\" />
    <Folder Include="ProductAggregate\" />
  </ItemGroup>

</Project>
